"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const staticRoot = path.join(__dirname, "../../main/resources/static");
const index = fs.readFileSync(path.join(staticRoot, "index.html"), "utf8");
const directory = fs.readFileSync(path.join(staticRoot, "help/help-directory.html"), "utf8");
const guide = fs.readFileSync(path.join(staticRoot, "help/viewer-guide.html"), "utf8");
const pdf = fs.readFileSync(path.join(staticRoot, "help/WSI-Viewer-Quick-Guide.pdf"));
const userGuide = fs.readFileSync(path.join(staticRoot, "help/user-guide.html"), "utf8");
const userGuidePdf = fs.readFileSync(path.join(staticRoot, "help/WSI-User-Administration-Guide.pdf"));

assert.match(userGuide, /WSI Comprehensive User/);
assert.match(userGuide, /X-WSI-User/);
assert.match(userGuide, /com\.wsi\.ops-dashboard/);
assert.match(userGuide, /Viewer Multi-view, channel viewer, and shortcuts/);
assert.match(userGuide, /Show channel viewer/);
assert.match(userGuide, /Synchronize viewers/);
assert.match(userGuide, /Left pane and Hierarchy/);
assert.match(userGuide, /Delete object/);
assert.match(userGuide, /Nuclear channel/);
assert.match(userGuide, /Heat Map/);
assert.equal(userGuidePdf.subarray(0, 5).toString("ascii"), "%PDF-");

assert.match(index, /id="help-directory-link"/);
assert.match(index, /window\.open\("\/help\/help-directory\.html", "_blank"\)/);
assert.match(index, /id="floating-shortcuts-legend"/);
assert.match(index, /max-height:\s*calc\(100vh - 24px\)/);
assert.match(index, /get\("admin"\) === "1"/);
assert.match(index, /Multi-view; Cell display; Display \(Show analysis, Brightness\/Contrast, overlay 400%–1%\); Set tool; Open Z-stack controller/);
assert.match(index, /Double-click channel max/);
assert.match(index, /Drag locked annotation/);
assert.match(index, /Drag channel histogram/);
assert.match(index, /id="classify-menu-button"/);
assert.match(index, /Object classification \(train\/load\/save\/apply to detections\)/);
assert.match(index, /Ctrl\+Shift\+D/);
assert.match(index, /⌘⇧D/);
assert.match(index, /Ctrl\+Shift\+P/);
assert.match(index, /⌘⇧P/);
assert.match(index, /Ctrl\+Shift\+S/);
assert.match(index, /⌘⇧S/);
assert.match(index, /Ctrl\+Alt\+S/);
assert.match(index, /Right-click image/);
assert.match(index, /Right-click annotation/);
assert.match(index, /Right-click cell/);
assert.match(index, /Lock\/Unlock Position, Set properties \(name, color, class, or create a class\), or Delete/);
assert.match(index, /Yes keeps them, No deletes them too, Cancel leaves everything/);
assert.match(index, /Slides, Image, Annotations, Hierarchy/);
assert.match(index, /Empty outline = hidden/);
assert.match(index, /Heat Map/);
assert.match(index, /Open Z-stack controller/);
assert.match(index, /Right-click channel viewer/);
assert.match(index, /Drag slide onto a pane/);
assert.match(index, /Click: this shortcuts legend\. Shift-click: Help directory\./);
assert.doesNotMatch(index, /id="user-guide-link"/);
assert.doesNotMatch(index, /window\.location\.assign\(url\)/);
assert.doesNotMatch(index, /if \(!opened\) window\.location\.assign/);

assert.match(directory, /id="dashboard-link"/);
assert.match(directory, /id="services-link"/);
assert.match(directory, /127\.0\.0\.1:8084\/services/);
assert.match(directory, /openOpsOrFallback\("\/"\)/);
assert.match(directory, /openOpsOrFallback\("\/services"\)/);
assert.match(directory, /\/local-operations\//);
assert.match(directory, /\/\?admin=1/);
assert.match(directory, /openFloatingAdminPalette/);
assert.match(directory, /id="user-guide-link"/);
assert.match(directory, /href="\/help\?v=20260911-persist-objects"/);
assert.match(directory, /id="viewer-quick-guide-link"/);
assert.match(directory, /href="\/help\/viewer-guide\.html\?v=20260911-persist-objects"/);
assert.match(directory, /id="admin-ops-guide-link"/);
assert.match(directory, /href="\/help\/admin-ops-guide\.html\?v=20260911-persist-objects"/);
assert.match(directory, /id="local-operations"/);
assert.match(directory, />Admin</);
assert.match(directory, /a, button \{[^}]*font-size:\s*14px/);
assert.match(directory, /a, button \{[^}]*appearance:\s*none/);
assert.match(directory, /target="_blank"/);
assert.match(directory, /rel="noopener noreferrer"/);

assert.match(guide, /<title>WSI Viewer Quick Guide<\/title>/);
assert.match(guide, /Multi-view/);
assert.match(guide, /Show channel viewer/);
assert.match(guide, /Open Z-stack controller/);
assert.match(guide, /Cell display/);
assert.match(guide, /Set tool/);
assert.match(guide, /Show analysis/);
assert.match(guide, /locked/);
assert.match(guide, /Hierarchy/);
assert.match(guide, /Yes<\/b> keeps them/);
assert.match(guide, /Nuclear channel \(recommended\)/);
assert.match(guide, /Heat Map/);
assert.match(guide, /empty outline means the channel is off/);
assert.match(guide, /Classify/);
assert.match(guide, /Object classification/);
assert.match(guide, /Pixel classification/);
assert.match(guide, /Synchronize viewers/);
assert.match(guide, /Ctrl\+Shift\+S/);
assert.match(guide, /id="close-guide"/);
assert.ok(guide.includes(">Close guide</button>"));
assert.ok(guide.includes("window.close()"));
assert.ok(guide.includes('if (!window.closed) window.location.assign("/")'));
assert.ok(guide.includes('href="/help"'));
assert.ok(guide.includes('href="/help/WSI-Viewer-Quick-Guide.pdf"'));
assert.ok(guide.includes(">Printable PDF</a>"));
assert.doesNotMatch(guide, /https?:\/\//);
assert.equal(pdf.subarray(0, 5).toString("ascii"), "%PDF-");
assert.ok(pdf.length > 1000, "packaged PDF must be nonempty");

console.log("authenticated viewer help contract checks passed");
